// Datos iniciales para Global Translators Studio
// Actualizados con los CVs reales de las practicantes de UNIFÉ
window.GT_DATA_INITIAL = {
  practicantes: [
    {
      id: "p1",
      nombre: "Maria Fernanda Olivares Ramón",
      rol: "Practicante de Traducción e Interpretación (EN / PT / ES)",
      universidad: "Universidad Femenina del Sagrado Corazón (UNIFÉ)",
      semestre: "2022 - Actual | 9no - 10mo Ciclo",
      nacionalidad: "Peruana",
      telefono: "(+51) 960 579 156",
      email: "olivaresramonfernanda@gmail.com",
      linkedin: "https://www.linkedin.com/in/mariaolivaresr",
      ubicacion: "Callao, Perú",
      idiomas: ["Español (Lengua materna)", "Inglés (C1)", "Portugués (B2)"],
      catTools: ["Trados Studio", "Subtitle Edit", "Photoshop", "Pack Office", "Google Drive", "Outlook"],
      horasCompletadas: 340,
      horasMeta: 480,
      avatar: "assets/avatars/avatar_p1.png",
      colorTag: "pink",
      cvUrl: "cvs/CV_Maria_Fernanda_Olivares.pdf",
      resumenCv: "Practicante de Traducción e Interpretación en la UNIFÉ con un sólido dominio del inglés y portugués. Comprometida con la precisión terminológica y la fidelidad cultural en proyectos de archivo, interpretación y subtitulaje.",
      educacion: [
        "2022 - ACTUAL: TRADUCCIÓN E INTERPRETACIÓN — Universidad Femenina del Sagrado Corazón (UNIFÉ)",
        "2021 - 2021: DISEÑO GRÁFICO — CIBERTEC"
      ],
      experiencia: [
        "23/03/2026 – 03/06/2026: PRACTICANTE — Oficina de Cooperación Internacional y Relaciones Interinstitucionales de UNIFÉ (Apoyo con la traducción de textos académicos y rol de intérprete en formación en eventos de interpretación).",
        "30/08/2025 – 26/09/2025: APOYO EN LOGÍSTICA — Jornada Científica Internacional de Traducción e Interpretación 2025 (UNIFÉ) (Difusión, publicidad y publicaciones en redes sobre la jornada).",
        "15/04/2023 – 02/07/2023: AUXILIAR DE APOYO — Biblioteca Nacional del Perú - Sede Abancay (Apoyo y organización de material educativo para personas con discapacidad visual, digitalización de libros).",
        "26/08/2023 – 09/12/2023: AUXILIAR DE APOYO — Biblioteca Municipal de San Borja (Organización de libros, apoyo a estudiantes del centro cultural, orientación en actividades)."
      ],
      aficiones: ["Saxofón", "Lectura", "Diseño Gráfico"],
      habilidades: ["Precisión terminológica", "Fidelidad cultural", "Subtitulaje (Subtitle Edit)", "Trados Studio", "Interpretación de enlace"]
    },
    {
      id: "p2",
      nombre: "Celine Lorena Bautista Ramos",
      rol: "Practicante de Traducción e Interpretación (EN / PT / ES)",
      universidad: "Universidad Femenina del Sagrado Corazón (UNIFÉ)",
      semestre: "2022 - Actual | Próxima a 10mo Ciclo",
      nacionalidad: "Peruana",
      telefono: "+51 924 193 856",
      email: "bautistalinna234@gmail.com",
      linkedin: "https://www.linkedin.com/in/celinebautista",
      ubicacion: "Lima, Perú",
      idiomas: ["Español (Lengua materna)", "Inglés: Intermedio (B2)", "Portugués: Intermedio (B2)"],
      catTools: ["Subtitle Edit", "Maquetación de Documentos", "Pack Office", "Google Drive"],
      horasCompletadas: 410,
      horasMeta: 480,
      avatar: "assets/avatars/avatar_p2.png",
      colorTag: "lavender",
      cvUrl: "cvs/CV_Celine_Lorena_Bautista.pdf",
      resumenCv: "Estudiante de Traducción e Interpretación próxima al décimo ciclo en UNIFÉ. Alto sentido de responsabilidad, proactividad y experiencia en maquetación editorial y evaluación lingüística en entornos multiculturales.",
      educacion: [
        "2022 - ACTUAL: TRADUCCIÓN E INTERPRETACIÓN — Universidad Femenina del Sagrado Corazón (UNIFÉ)"
      ],
      experiencia: [
        "06/04/2026 – 05/07/2026: PRACTICANTE — Revista Comunifé (Traducción de textos especializados del español al inglés en diversas áreas temáticas, maquetación y preparación de documentos traducidos para su entrega).",
        "20/01/2026 – 15/04/2026: OPERATIONS CUSTOMER EXPERT — Teleperformance (Análisis de contenidos en inglés y portugués conforme a lineamientos establecidos, evaluación lingüística y contextual en entornos multiculturales).",
        "08/2023 – 12/2023: VOLUNTARIADO — HANOPREM (Presentación de diferentes temas para jóvenes con discapacidad intelectual, elaboración de materiales adaptados).",
        "12/2022 – 03/2023: VOLUNTARIADO — Programa de Liderazgo y Voluntariado Ambiental Juvenil (Ministerio del Ambiente, promoción de temas ambientales y enfoque de género)."
      ],
      aficiones: ["Lectura", "Voluntariado", "Senderismo"],
      habilidades: ["Traducción especializada ES-EN", "Maquetación y entrega de documentos", "Evaluación lingüística contextual", "Responsabilidad y proactividad"]
    },
    {
      id: "p3",
      nombre: "Sophia Camila Cabrera Zarate",
      rol: "Practicante de Traducción e Interpretación (EN / FR / ES)",
      universidad: "Universidad Femenina del Sagrado Corazón (UNIFÉ)",
      semestre: "2022 - Actual | Último Ciclo",
      nacionalidad: "Peruana",
      telefono: "(+51) 987 985 138",
      email: "sofiacamilacabrera@gmail.com",
      linkedin: "https://www.linkedin.com/in/sophiacabreraz",
      ubicacion: "Lima, Perú",
      idiomas: ["Español (Lengua materna)", "Inglés (C1)", "Francés (B2)"],
      catTools: ["SDL Trados", "Subtitle Edit", "Word", "Outlook", "Google Drive"],
      horasCompletadas: 390,
      horasMeta: 480,
      avatar: "assets/avatars/avatar_p3.png",
      colorTag: "mint",
      cvUrl: "cvs/CV_Sophia_Camila_Cabrera.pdf",
      resumenCv: "Estudiante de último ciclo de Traducción e Interpretación en UNIFÉ. Apasionada por su carrera, con destacada experiencia en traducción académica, edición bilingüe de revistas científicas y uso de SDL Trados.",
      educacion: [
        "2022 - ACTUAL: TRADUCCIÓN E INTERPRETACIÓN — UNIFÉ (Lima, Perú)",
        "2015 - 2022: CURSO AVANZADO DE INGLÉS — Británico (Lima, Perú)"
      ],
      experiencia: [
        "2026: TRADUCTORA ES-EN — Revista Académica COMUNIFÉ: 'Efectos de la pandemia de COVID-19 en la representación social del Perú en Chile'.",
        "2026: TRADUCTORA ES-EN — Revista Académica COMUNIFÉ: 'Frames de los latinoamericanos inmigrantes en España y su relación con los estereotipos'.",
        "Traducción y edición bilingüe de artículos científicos y sociopolíticos para publicación universitaria indexada."
      ],
      aficiones: ["Traducción académica", "Investigación lingüística", "Lectura sociopolítica"],
      habilidades: ["Traducción especializada inglés-español", "SDL Trados", "Subtitle Edit", "Rigor en fuentes y citas académicas"]
    },
    {
      id: "p4",
      nombre: "Landys Brunella Gonzales Torres",
      rol: "Practicante de Traducción e Interpretación (EN / FR / ES)",
      universidad: "Universidad Femenina del Sagrado Corazón (UNIFÉ)",
      semestre: "2022 - Actual | 9no - 10mo Ciclo",
      nacionalidad: "Peruana",
      telefono: "(+51) 950 205 401",
      email: "brunellagonzales24@gmail.com",
      linkedin: "https://www.linkedin.com/in/brunellagonzales",
      ubicacion: "Lima, Perú",
      idiomas: ["Español (Lengua materna)", "Inglés: Intermedio", "Francés: Intermedio"],
      catTools: ["Canva", "Subtitle Edit", "Microsoft Office", "Google Drive"],
      horasCompletadas: 420,
      horasMeta: 480,
      avatar: "assets/avatars/avatar_p4.png",
      colorTag: "sky",
      cvUrl: "cvs/CV_Landys_Brunella_Gonzales.pdf",
      resumenCv: "Estudiante de Traducción e Interpretación en la UNIFÉ. Experiencia destacada como intérprete consecutiva en ferias internacionales (Expo Plast / Pack Perú), traducción de joyería EN-FR y mediación intercultural.",
      educacion: [
        "2022 - ACTUAL: TRADUCCIÓN E INTERPRETACIÓN — Universidad Femenina del Sagrado Corazón (UNIFÉ)"
      ],
      experiencia: [
        "19/08/2026 – 20/08/2026: INTÉRPRETE CONSECUTIVA (Practicante) — 11va Feria Expo Plast Perú & 6° Pack Perú Expo (PERU EXPO 2026) (Comunicación y enlace entre empresarios e interesados).",
        "02/06/2026 – 10/07/2026: SERVICIO DE TRADUCCIÓN (Practicante) — MIKING LLC (Documentos especializados en joyería y diamantes en combinación lingüística inglés-francés).",
        "28/05/2026: INTÉRPRETE DE ENLACE (Practicante) — Newton College (Comunicación entre docentes angloparlantes y padres de familia del nivel secundario).",
        "Abril 2026 – Julio 2026: SERVICIO DE TRADUCCIÓN (Practicante) — Revista COMUNIFÉ (Documentos especializados y revistas universitarias español-inglés).",
        "Asistente de Producción en Eventos Corporativos — Alucina ITL Comunicación Integral S.A.C.",
        "Voluntariados — Asistente en Secretaría I.E 1207 Sagrado Corazón de Jesús & Casa de Reposo Los Anturios."
      ],
      aficiones: ["Canto", "Danza", "Club de lectura", "Deportes de alto riesgo", "Viajes", "Subtitular", "Películas y series"],
      habilidades: ["Interpretación consecutiva", "Interpretación de enlace", "Traducción inglés-francés / español", "Mediación intercultural", "Liderazgo de equipos"]
    },
    {
      id: "p5",
      nombre: "Fatima Valentina Gallegos Tornero",
      rol: "Practicante de Traducción e Interpretación (EN / FR / ES)",
      universidad: "Universidad Femenina del Sagrado Corazón (UNIFÉ)",
      semestre: "2022 - Actual | 9no Ciclo",
      nacionalidad: "Peruana",
      telefono: "(+51) 992 826 616",
      email: "fatimavgt2@gmail.com",
      linkedin: "https://www.linkedin.com/in/fatima-gallegos-1011812a0",
      ubicacion: "Lima, Perú",
      idiomas: ["Español (Lengua materna)", "Inglés (C2 - Dominio Eficaz)", "Francés (C1 - Avanzado)"],
      catTools: ["Trados Studio", "Subtitle Edit", "Microsoft Office", "Google Drive", "Outlook"],
      horasCompletadas: 360,
      horasMeta: 480,
      avatar: "assets/avatars/avatar_p5.png",
      colorTag: "rose",
      cvUrl: "cvs/CV_Fatima_Valentina_Gallegos.pdf",
      resumenCv: "Estudiante del noveno ciclo de la carrera de Traducción e Interpretación en la UNIFÉ. Apasionada por los idiomas y la comunicación, responsable y comprometida. Prioriza la precisión, claridad y calidad en proyectos de enlace y traducción.",
      educacion: [
        "2022 - ACTUAL: TRADUCCIÓN E INTERPRETACIÓN DE IDIOMAS — Universidad Femenina del Sagrado Corazón (UNIFÉ) (Lima, Perú)"
      ],
      experiencia: [
        "01/01/2026 – 31/03/2026: ATENCIÓN AL CLIENTE — Cafeteria Sweet Frezze (Atención y entrega de productos en tienda, cocina y estándares de servicio al cliente).",
        "15/09/2024 – 31/12/2024: CLASES A DOMICILIO — RYS clases a domicilio (Refuerzo escolar para alumnos de primaria, materiales adecuados, docencia bilingüe en inglés A1-A2 y francés A1-B2).",
        "03/04/2023 – 16/11/2023: AYUDANTE DE PROFESORA Y AUXILIAR (Voluntariado) — Colegio Santiago de Surco N.° 7087 (Certificado por UGEL 07 – Curso UNIFÉ).",
        "03/04/2023 – 16/11/2023: INTERPRETACIÓN DE ENLACE (Practicante) — Newton College Early Years (Certificado por el Newton College – Prácticas UNIFÉ)."
      ],
      aficiones: ["Docencia de idiomas", "Comunicación pedagógica", "Lectura literaria"],
      habilidades: ["Inglés C2 & Francés C1", "Interpretación de enlace", "Trados Studio", "Subtitle Edit", "Precisión y rigor terminológico"]
    },
    {
      id: "p6",
      nombre: "Arihana Jelena Altamirano Guevara",
      rol: "Practicante de Traducción e Interpretación (EN / FR / ES)",
      universidad: "Universidad Femenina del Sagrado Corazón (UNIFÉ)",
      semestre: "2022 - Actual | La Molina, Lima",
      nacionalidad: "Peruana",
      telefono: "(+51) 942 639 809",
      email: "aria030910@gmail.com",
      linkedin: "https://www.linkedin.com/in/arihana-altamirano",
      ubicacion: "Lima, Perú",
      idiomas: ["Español (Lengua materna)", "Inglés: Intermedio", "Francés: Básico"],
      catTools: ["Canva", "Subtitle Edit", "Microsoft Office", "Google Drive", "Outlook", "WhatsApp Business"],
      horasCompletadas: 380,
      horasMeta: 480,
      avatar: "assets/avatars/avatar_p6.png",
      colorTag: "amber",
      cvUrl: "cvs/CV_Arihana_Jelena_Altamirano.pdf",
      resumenCv: "Estudiante de Traducción e Interpretación en la UNIFÉ, apasionada por los idiomas, las culturas y la traducción audiovisual. Experiencia como voluntaria de inglés y asistente de producción corporativa con solvencia comunicativa y trabajo en equipo.",
      educacion: [
        "2022 - ACTUAL: TRADUCCIÓN E INTERPRETACIÓN — UNIVERSIDAD FEMENINA DEL SAGRADO CORAZÓN (UNIFÉ)"
      ],
      experiencia: [
        "07/2023 – Esporádicamente a 2026: ASISTENTE DE PRODUCCIÓN EN EVENTOS CORPORATIVOS — Alucina ITL Comunicación Integral S.A.C (Comunicación intercultural, resolución de requerimientos y trabajo bajo presión).",
        "Abril – Julio 2026: PRÁCTICAS PRE-PROFESIONALES — Revista Comunifé (Traducción de artículos académicos especializados del español al inglés y análisis terminológico).",
        "05/2026: PRÁCTICAS PRE-PROFESIONALES — Evento de Interpretación en Newton College (Servicio de interpretación de enlace del español al inglés en reunión de padres).",
        "22 – 23/06/2026: PRÁCTICAS PRE-PROFESIONALES — Evento de Interpretación para University of MARY (Servicio de interpretación de enlace del español al inglés en colegio Alegría Del Señor).",
        "25 – 27/09/2025: APOYO LOGÍSTICO Y EQUIPO DE ORGANIZACIÓN — Jornada Científica Internacional de Traducción e Interpretación (UNIFÉ).",
        "09/2023 – 12/2023: VOLUNTARIADO — Profesora de inglés (Clases de inglés completas para 4to y 5to de secundaria y material didáctico)."
      ],
      aficiones: ["Canto", "Organizar viajes y viajar", "Doblaje y Subtitulación"],
      habilidades: ["Traducción audiovisual & subtitulaje", "Interpretación de enlace ES-EN", "Maquetación y diseño en Canva", "Atención intercultural a clientes"]
    }
  ],

  entregas: [
    {
      id: "ent-sm-1",
      titulo: "Preservando Historias San Mateo: Transcripción y Traducción de Relatos Orales de Ancianos (Ep. 01 & 02)",
      practicanteId: "p1",
      practicanteNombre: "Maria Fernanda Olivares Ramón",
      parIdiomas: "ES ➔ EN",
      categoria: "Patrimonio / Testimonial",
      fechaLimite: "2026-10-02",
      horaLimite: "16:00",
      prioridad: "Express",
      estado: "en-progreso",
      progreso: 78,
      palabras: 5400,
      documentoUrl: "https://drive.google.com/sample-san-mateo-oral-history-01",
      notas: "Proyecto Preservando Historias San Mateo. Cuidar la preservación de modismos y valor patrimonial de los ancianos."
    },
    {
      id: "ent-sm-2",
      titulo: "Preservando Historias San Mateo: Glosario Toponímico y de Medicina Tradicional",
      practicanteId: "p4",
      practicanteNombre: "Landys Brunella Gonzales Torres",
      parIdiomas: "Quechua/ES ➔ ES/EN",
      categoria: "Terminología / San Mateo",
      fechaLimite: "2026-10-05",
      horaLimite: "18:00",
      prioridad: "Urgente",
      estado: "pendiente",
      progreso: 25,
      palabras: 3200,
      documentoUrl: "https://drive.google.com/sample-san-mateo-glosario",
      notas: "Proyecto Preservando Historias San Mateo. Validar fitonimia y nombres de parajes con comuneros."
    },
    {
      id: "ent-sm-3",
      titulo: "Preservando Historias San Mateo: Subtitulado Bilingüe Archivo Audiovisual Comunitario",
      practicanteId: "p3",
      practicanteNombre: "Sophia Camila Cabrera Zarate",
      parIdiomas: "ES ➔ EN",
      categoria: "Audiovisual / San Mateo",
      fechaLimite: "2026-09-30",
      horaLimite: "12:00",
      prioridad: "Normal",
      estado: "revision",
      progreso: 92,
      palabras: 2800,
      documentoUrl: "https://drive.google.com/sample-san-mateo-subtitulos",
      notas: "Proyecto Preservando Historias San Mateo. Sincronización con el archivo de video histórico."
    },
    {
      id: "ent-1",
      titulo: "Subtitulaje Serie Documental Netflix: Océanos Vivos (Ep. 03)",
      practicanteId: "p1",
      practicanteNombre: "Maria Fernanda Olivares Ramón",
      parIdiomas: "EN ➔ ES",
      categoria: "Audiovisual",
      fechaLimite: "2026-10-02",
      horaLimite: "17:00",
      prioridad: "Urgente",
      estado: "en-progreso",
      progreso: 65,
      palabras: 4200,
      documentoUrl: "https://drive.google.com/file/d/sample-subtitles-01",
      notas: "Verificar sincronización con el corte final. Mantener límite de 37 caracteres por línea."
    },
    {
      id: "ent-2",
      titulo: "Traducción Especializada Revista Comunifé: Impacto Social y Salud Pública",
      practicanteId: "p2",
      practicanteNombre: "Celine Lorena Bautista Ramos",
      parIdiomas: "ES ➔ EN",
      categoria: "Académica / Revista",
      fechaLimite: "2026-10-04",
      horaLimite: "14:00",
      prioridad: "Normal",
      estado: "en-progreso",
      progreso: 50,
      palabras: 3100,
      documentoUrl: "https://drive.google.com/file/d/sample-comunife-celine",
      notas: "Revisar estilo editorial UNIFÉ y normas APA 7ma edición."
    },
    {
      id: "ent-3",
      titulo: "Traducción de Artículos Sociopolíticos: Estereotipos e Inmigración",
      practicanteId: "p3",
      practicanteNombre: "Sophia Camila Cabrera Zarate",
      parIdiomas: "ES ➔ EN",
      categoria: "Académica / COMUNIFÉ",
      fechaLimite: "2026-10-06",
      horaLimite: "18:00",
      prioridad: "Normal",
      estado: "pendiente",
      progreso: 20,
      palabras: 4800,
      documentoUrl: "https://drive.google.com/file/d/sample-comunife-sophia",
      notas: "Artículo sobre marcos de inmigrantes latinoamericanos en Europa."
    },
    {
      id: "ent-4",
      titulo: "Traducción Técnica Especializada en Joyería y Gemas MIKING LLC",
      practicanteId: "p4",
      practicanteNombre: "Landys Brunella Gonzales Torres",
      parIdiomas: "EN ➔ FR",
      categoria: "Comercial / Técnica",
      fechaLimite: "2026-09-30",
      horaLimite: "12:00",
      prioridad: "Express",
      estado: "revision",
      progreso: 90,
      palabras: 3400,
      documentoUrl: "https://drive.google.com/file/d/sample-miking-landys",
      notas: "Terminología específica de corte de diamantes y metales preciosos."
    },
    {
      id: "ent-sm-5",
      titulo: "Preservando Historias San Mateo: Protocolo Terminológico para Intérpretes de Enlace",
      practicanteId: "p5",
      practicanteNombre: "Fatima Valentina Gallegos Tornero",
      parIdiomas: "ES ➔ FR / EN",
      categoria: "Patrimonio / Enlace",
      fechaLimite: "2026-10-04",
      horaLimite: "17:00",
      prioridad: "Normal",
      estado: "pendiente",
      progreso: 40,
      palabras: 2900,
      documentoUrl: "https://drive.google.com/sample-san-mateo-guia-interpretes",
      notas: "Proyecto Preservando Historias San Mateo. Estandarización de términos de enlace cultural y memoria histórica."
    },
    {
      id: "ent-sm-6",
      titulo: "Preservando Historias San Mateo: Subtitulado y Doblaje Piloto de Testimonios Comunitarios",
      practicanteId: "p6",
      practicanteNombre: "Arihana Jelena Altamirano Guevara",
      parIdiomas: "ES ➔ EN",
      categoria: "Audiovisual / San Mateo",
      fechaLimite: "2026-10-06",
      horaLimite: "15:00",
      prioridad: "Express",
      estado: "en-progreso",
      progreso: 65,
      palabras: 3100,
      documentoUrl: "https://drive.google.com/sample-san-mateo-subtitulado-audiovisual",
      notas: "Proyecto Preservando Historias San Mateo. Sincronización y subtitulaje accesible para archivo sonoro de San Mateo."
    }
  ],

  coachingSessions: [
    {
      id: "c1",
      practicanteId: "p1",
      practicanteNombre: "Maria Fernanda Olivares Ramón",
      tipo: "Mock Interview (Entrevista en Inglés / Portugués)",
      coach: "Lic. Andrea Paz (Head of Talent)",
      fecha: "2026-10-03",
      hora: "10:30",
      estado: "programada",
      objetivo: "Simulacro de entrevista técnica para agencia internacional de localización y subtitulaje.",
      acuerdos: "Preparar 3 ejemplos de proyectos con metodología STAR y métricas de calidad en Subtitle Edit.",
      enlaceSala: "https://meet.google.com/gts-coaching-p1",
      calificacion: null
    },
    {
      id: "c2",
      practicanteId: "p2",
      practicanteNombre: "Celine Lorena Bautista Ramos",
      tipo: "Optimización de CV & Portfolio de Textos Especializados",
      coach: "Mg. Fernando Valenzuela",
      fecha: "2026-10-05",
      hora: "16:00",
      estado: "programada",
      objetivo: "Estructuración de muestras de traducción para la Revista Comunifé y perfil ATS en portugués.",
      acuerdos: "Redactar casos de estudio anonimizados de textos académicos.",
      enlaceSala: "https://meet.google.com/gts-coaching-p2",
      calificacion: null
    },
    {
      id: "c3",
      practicanteId: "p3",
      practicanteNombre: "Sophia Camila Cabrera Zarate",
      tipo: "LinkedIn Pro & Marca Personal para Traductoras",
      coach: "Lic. Andrea Paz (Head of Talent)",
      fecha: "2026-09-27",
      hora: "11:00",
      estado: "completada",
      objetivo: "Perfil optimizado con palabras clave de traducción académica e investigación sociopolítica.",
      acuerdos: "Publicar un extracto sobre los artículos publicados en COMUNIFÉ.",
      enlaceSala: "https://meet.google.com/gts-coaching-p3",
      calificacion: "Sobresaliente (9.8/10) - Extraordinario rigor terminológico y solvencia lingüística."
    },
    {
      id: "c4",
      practicanteId: "p4",
      practicanteNombre: "Landys Brunella Gonzales Torres",
      tipo: "Preparación para Interpretación Consecutiva & Ferias Internacionales",
      coach: "Director Mateo Castillo",
      fecha: "2026-10-07",
      hora: "15:00",
      estado: "programada",
      objetivo: "Técnicas de toma de notas, control de estrés en interpretación de enlace y negociación de honorarios.",
      acuerdos: "Practicar speech de 3 minutos sobre comercio exterior e industria ferial.",
      enlaceSala: "https://meet.google.com/gts-coaching-p4",
      calificacion: null
    },
    {
      id: "c5",
      practicanteId: "p5",
      practicanteNombre: "Fatima Valentina Gallegos Tornero",
      tipo: "Mock Interview Internacional & Certificación C2",
      coach: "Lic. Andrea Paz (Head of Talent)",
      fecha: "2026-10-09",
      hora: "10:30",
      estado: "programada",
      objetivo: "Preparación para postulaciones en organismos internacionales y agencias de la Unión Europea.",
      acuerdos: "Simular preguntas técnicas de interpretación de enlace y traducción simultánea.",
      enlaceSala: "https://meet.google.com/gts-coaching-p5",
      calificacion: null
    },
    {
      id: "c6",
      practicanteId: "p6",
      practicanteNombre: "Arihana Jelena Altamirano Guevara",
      tipo: "Portafolio Audiovisual & Estrategia en Traducción y Doblaje",
      coach: "Mg. Fernando Valenzuela",
      fecha: "2026-10-10",
      hora: "16:30",
      estado: "programada",
      objetivo: "Montaje de demo reel de subtitulado con Subtitle Edit y Canva para agencias de streaming.",
      acuerdos: "Exportar 2 fragmentos de 45 segundos con subtítulos sincronizados y glosario de términos.",
      enlaceSala: "https://meet.google.com/gts-coaching-p6",
      calificacion: null
    }
  ],

  roadmapSteps: [
    { id: "r1", titulo: "CV Formato Internacional ATS", desc: "Diseño limpio en inglés y español con verbos de acción.", hecho: true },
    { id: "r2", titulo: "Perfil LinkedIn Bilingüe Optimizado", desc: "Titular estratégico, extracto con palabras clave y sección de destacados.", hecho: true },
    { id: "r3", titulo: "Portafolio de Traducción con Muestras Limpias", desc: "Textos origen y meta autorizados demostrando precisión y estilo.", hecho: true },
    { id: "r4", titulo: "Simulacro de Entrevista Técnica (Mock Interview)", desc: "Roleplay de resolución de imprevistos, plazos ajustados y pruebas de traducción.", hecho: false },
    { id: "r5", titulo: "Estrategia de Prospección y Agencias Globales", desc: "Postulación a agencias en Proz, TranslatorsCafe y LinkedIn.", hecho: false }
  ],

  glosario: [
    { id: "g1", origen: "Severability Clause", meta: "Cláusula de divisibilidad / nulidad parcial", campo: "Jurídico", notas: "Común en contratos societarios." },
    { id: "g2", origen: "Informed Consent Form (ICF)", meta: "Formulario de consentimiento informado", campo: "Médico", notas: "No traducir como 'forma de consentimiento'." },
    { id: "g3", origen: "Lip-sync dubbing", meta: "Doblaje con sincronía labial", campo: "Audiovisual", notas: "Requiere ajuste riguroso de longitud silábica." },
    { id: "g4", origen: "Call to Action (CTA)", meta: "Llamada a la acción", campo: "Marketing", notas: "Adaptar según tono de la marca (Tú / Usted)." },
    { id: "g5", origen: "Consecutive Interpreting", meta: "Interpretación consecutiva", campo: "Interpretación", notas: "Modalidad utilizada en ferias y eventos bilaterales." }
  ],

  stickyNotes: [
    { id: "n1", color: "pink", texto: "🌸 Recordatorio: Equipo de UNIFÉ, registrar horas de prácticas semanales para acreditar ante coordinación." },
    { id: "n2", color: "lavender", texto: "💜 Proyecto San Mateo: Las transcripciones orales tienen prioridad en la mesa de revisión QA." },
    { id: "n3", color: "mint", texto: "🌿 Taller de Trados Studio y Subtitle Edit este viernes a las 4:00 PM vía Google Meet." }
  ],

  excelTemplateData: [
    { "ID": "PRAC-001", "Practicante": "Maria Fernanda Olivares Ramón", "Especialidad": "Audiovisual / Intérprete", "Idiomas": "ES (Nativo), EN (C1), PT (B2)", "Horas Acumuladas": 340, "Meta Horas": 480, "Estado CV": "Aprobado (UNIFÉ)", "Próximo Coaching": "Mock Interview (03/10)" },
    { "ID": "PRAC-002", "Practicante": "Celine Lorena Bautista Ramos", "Especialidad": "Textos Especializados / Comunifé", "Idiomas": "ES (Nativo), EN (B2), PT (B2)", "Horas Acumuladas": 410, "Meta Horas": 480, "Estado CV": "Aprobado (UNIFÉ)", "Próximo Coaching": "Portfolio Comunifé (05/10)" },
    { "ID": "PRAC-003", "Practicante": "Sophia Camila Cabrera Zarate", "Especialidad": "Traducción Académica / COMUNIFÉ", "Idiomas": "ES (Nativo), EN (C1), FR (B2)", "Horas Acumuladas": 390, "Meta Horas": 480, "Estado CV": "Aprobado (UNIFÉ)", "Próximo Coaching": "Completado (27/09)" },
    { "ID": "PRAC-004", "Practicante": "Landys Brunella Gonzales Torres", "Especialidad": "Interpretación Consecutiva / Ferias", "Idiomas": "ES (Nativo), EN (Intermedio), FR (Intermedio)", "Horas Acumuladas": 420, "Meta Horas": 480, "Estado CV": "Aprobado (UNIFÉ)", "Próximo Coaching": "Interpretación Ferias (07/10)" },
    { "ID": "PRAC-005", "Practicante": "Fatima Valentina Gallegos Tornero", "Especialidad": "Interpretación Enlace / EN C2 FR C1", "Idiomas": "ES (Nativo), EN (C2), FR (C1)", "Horas Acumuladas": 360, "Meta Horas": 480, "Estado CV": "Aprobado (UNIFÉ)", "Próximo Coaching": "Mock Interview C2 (09/10)" },
    { "ID": "PRAC-006", "Practicante": "Arihana Jelena Altamirano Guevara", "Especialidad": "Audiovisual & Eventos Corporativos", "Idiomas": "ES (Nativo), EN (Intermedio), FR (Básico)", "Horas Acumuladas": 380, "Meta Horas": 480, "Estado CV": "Aprobado (UNIFÉ)", "Próximo Coaching": "Portfolio Subtitulado (10/10)" }
  ]
};
